Feature/#37 eintrag bearbeiten
fonzerelly/shared-shopper pull request #43
Opened 2021-05-10 08:10 UTC by philippkollmar

2021-05-12 00:29 UTC, fonzerelly requested changes
Bitte berücksichtigen Sie meine Kommentare, damit der Codeein wenig an Lesbarkeit gewinnt. 

Zögern Sie bitte nicht, mich bei Frage zu kontaktieren.

2021-05-12 00:29 UTC, fonzerelly commented on src/Components/Products/ProductChange.tsx
> +    const [edit, setEdit] = useState (1);
Bitte nutzen Sie statt einer Zahl ein enum um zwischen den beiden Modi zu unterscheiden. Die enums können sie mit aussagekräftigen namen belegen, so dass der Code dadurch wesentlich verständlicher werden sollte:
https://www.typescriptlang.org/docs/handbook/enums.html

2021-05-12 00:29 UTC, fonzerelly commented on src/Components/Products/ProductChange.tsx
> +            <PencilIcon2 onClick = {() => editProduct(1)} className={"pencil" + String(edit)} />
mit den enums könnten sie dann aus editProduct auch eine switchMode-funktion machen, die gar keinen Parameter entgegen nehmen muss, sondern basierend auf dem aktuellen wert von "edit" (was übrigens besser componentMode hieße) einfach den zweiten enum-Wert als state setzt. Das wäre wohl auch etwas dass man gut per unittest testen können sollte.

2021-05-12 00:29 UTC, fonzerelly commented on src/Components/Products/products.css
> +.ListInput2{
Da sich ListInput2 auf die Anzahl eines Eintrags bezieht, wäre vielleicht ein Name wie count besser geeignet. außerdem möchte ich sie ermutigen lieber die BEM-Schreibweise für CSS-Klassen zu verwenden, um etwaige namenskollisionen und Performance-probleme zu vermeiden:
http://getbem.com/introduction/

in diesem fall wäre daher der Klassenname eher
Product--count

2021-05-12 00:29 UTC, fonzerelly commented on src/Components/Products/products.css
> +.ListInput3{
ähnlich dem vorherigen Beispiel würde sich hier vielleicht Product--label anbieten.

wobei ich es ungewöhnlich finde CSS-Klassen mit Großbuchstaben zu bezeichnen.

2021-05-12 00:29 UTC, fonzerelly commented on src/List/List.css
> +
wofür so viele leerzeilen? Falls unklar, bitte löschen?

2021-05-12 00:29 UTC, fonzerelly commented on src/ShoppingList/ShoppingList.tsx
> +            <Link to="/list/shoppinglist/bearbeiten"><button className={ toggleState === 1 ? "tabs active-tabs" : "tabs" } onClick={() => toggleTab(1)}>Bearbeiten</button></Link>
Auch für den ToggleState bitte ein sprechendes enum einführen.

2021-05-12 00:29 UTC, fonzerelly commented on src/ShoppingList/ShoppingList.tsx
> +                <ProductBuyChecked name="Kekse" amount="3"/>
Erwarten Sie große unterschiede zwischen ProductBuy und ProductBuyChecked, dass sich zwei unterschiedliche Komponenten lohnen? Meine Einschätzung wäre, dass es genügt einen Parameter zu übergeben, der das Aussehen und Verhalten steuert.

2021-05-17 19:30 UTC, closed without merging

2021-05-17 19:31 UTC, HeStoIeMyName commented
In bugfix #45 gemergt